const books = [
  {
    "ID": 1,
    "Link": "https://pdfobject.com/pdf/sample.pdf",
    "Title": "furqan rocks.",
    "Author": "amir hamzah",
    "Publication Date": 2011,
    "Category/Genre": "fun",
    "Short Summary/Description": "",
    "Language": "kashmiri",
    "Keywords(at least 3)": "hello,how are you",
    "Publisher": "",
    "": "",
  },
  {
    "ID": 2,
    "Link": "https://pdfobject.com/pdf/sample.pdf",
    "Title": "areeba furqan",
    "Author": "amir hamzah",
    "Publication Date": 2011,
    "Category/Genre": "fun",
    "Short Summary/Description": "",
    "Language": "kashmiri",
    "Keywords(at least 3)": "hello,how are you",
    "Publisher": "",
    "": "*Required",
  },
  {
    "ID": 3,
    "Link": "https://pdfobject.com/pdf/sample.pdf",
    "Title": "hello world ",
    "Author": "amir hamzah",
    "Publication Date": 2011,
    "Category/Genre": "fun",
    "Short Summary/Description": "",
    "Language": "kashmiri",
    "Keywords(at least 3)": "hello,how are you",
    "Publisher": "",
    "": "",
  },
  {
    "ID": 4,
    "Link": "https://pdfobject.com/pdf/sample.pdf",
    "Title": "hello world ",
    "Author": "amir hamzah",
    "Publication Date": 2011,
    "Category/Genre": "fun",
    "Short Summary/Description": "",
    "Language": "kashmiri",
    "Keywords(at least 3)": "hello,how are you",
    "Publisher": "",
    "": "",
  },
  {
    "ID": 5,
    "Link": "https://pdfobject.com/pdf/sample.pdf",
    "Title": "hello world ",
    "Author": "amir hamzah",
    "Publication Date": 2011,
    "Category/Genre": "fun",
    "Short Summary/Description": "",
    "Language": "kashmiri",
    "Keywords(at least 3)": "hello,how are you",
    "Publisher": "",
    "": "",
  },
];

export default books;